title: Angularity
version: 0.0.1
 # baseurl: http://angularity.github.io
canonifyurls: true
publishdir: ../
MetaDataFormat: yaml
footnotereturnlinkcontents: "â†©"

theme: techdocshugotheme

 #permalinks:
 #  post: /:year/:month/:title/

params:
  Subtitle: An opinionated AngularJs build tool
  AuthorName: angularity
  GitHubUser: angularity
  GitHubRepo: node-angularity
  GithubDocEditPrefix: https://github.com/angularity/angularity.github.io/
  GitHubPagesBaseUrl: /
  GoogleAnalyticsId: UA-37884921-1
  GoogleAnalyticsDomain: bguiz.com
  RootRedirect:
    Url: /about/mission
    Name: Angularity

indexes:
  category: categories
  tag: tags

menu:
  main:
    - Name: About
      Weight: 1000
      Identifier: about
    - Name: Getting Started
      Weight: 2000
      Identifier: start
    - Name: Task Reference
      Weight: 3000
      Identifier: tasks
